### ISSUE TITLE
Hello ,have you run the correct result about python GBT pipeline.py,I have something in trouble about the chkfopen(),may be something wrong in prepsubband

### ISSUE THREAD

**Issue by Tom111-lhx** [W-Hsu/ASC21-preliminary#1]

**Comment by W-Hsu** [comment]
Didn't encounter your problem. Can you upload a screenshot of your log file?

**Comment by Tom111-lhx** [comment]
ok ,is this dedisperse.log







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "anonymous"<notifications@github.com&gt;; 
发送时间: 2021年1月7日(星期四) 下午3:40
收件人: "W-Hsu/ASC21-preliminary"<ASC21-preliminary@noreply.github.com&gt;; 
抄送: "数学1李昊翕2019302998"<2388979406@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [W-Hsu/ASC21-preliminary] Hello ,have you run the correct result about python GBT pipeline.py,I have something in trouble about the chkfopen(),may be something wrong in prepsubband (#1)





 
Didn't encounter your problem. Can you upload a screenshot of your log file?

**Comment by Tom111-lhx** [comment]
`   'Sband_DM17.75.sub16'
   'Sband_DM17.75.sub17'
   'Sband_DM17.75.sub18'
   'Sband_DM17.75.sub19'
   'Sband_DM17.75.sub20'
   'Sband_DM17.75.sub21'
   'Sband_DM17.75.sub22'
   'Sband_DM17.75.sub23'
   'Sband_DM17.75.sub24'
   'Sband_DM17.75.sub25'
   'Sband_DM17.75.sub26'
   'Sband_DM17.75.sub27'
   'Sband_DM17.75.sub28'
   'Sband_DM17.75.sub29'
   'Sband_DM17.75.sub30'
   'Sband_DM17.75.sub31'
numout=531000/n
De-dispersing using:
       Subbands = 32
     Average DM = 17.75

^MAmount complete =   0%^MAmount complete =   1%^MAmount complete =   2%^MAmount complete =   3%^MAmount complete =   4%^MAmount complete =   5%^MAmount complete =   6%^MAmount complete =   7%^MAmount complete =   8%^MAmount complete =   9%^MAmount complete =  10%^MAmount complete =  11%^MAmount complete =  12%^MAmount complete =  13%^MAmount complete =  14%^MAmount complete =  15%^MAmount complete =  16%^MAmount complete =  17%^MAmount complete =  18%^MAmount complete =  19%^MAmount complete =  20%^MAmount complete =  21%^MAmount complete =  22%^MAmount complete =  23%^MAmount complete =  24%^MAmount complete =  25%^MAmount complete =  26%^MAmount complete =  27%^MAmount complete =  28%^MAmount complete =  29%^MAmount complete =  30%^MAmount complete =  31%^MAmount complete =  32%^MAmount complete =  33%^MAmount complete =  34%^MAmount complete =  35%^MAmount complete =  36%^MAmount complete =  37%^MAmount complete =  38%^MAmount complete =  39%^MAmount complete =  40%^MAmount complete =  41%^MAmount complete =  42%^MAmount complete =  43%^MAmount complete =  44%^MAmount complete =  45%^MAmount complete =  46%^MAmount complete =  47%^MAmount complete =  48%^MAmount complete =  49%^MAmount complete =  50%^MAmount complete =  51%^MAmount complete =  52%^MAmount complete =  53%^MAmount complete =  54%^MAmount complete =  55%^MAmount complete =  56%^MAmount complete =  57%^MAmount complete =  58%^MAmount complete =  59%^MAmount complete =  60%^MAmount complete =  61%^MAmount complete =  62%^MAmount complete =  63%^MAmount complete =  64%^MAmount complete =  65%^MAmount complete =  66%^MAmount complete =  67%^MAmount complete =  68%^MAmount complete =  69%^MAmount complete =  70%^MAmount complete =  71%^MAmount complete =  72%^MAmount complete =  73%^MAmount complete =  74%^MAmount complete =  75%^MAmount complete =  76%^MAmount complete =  77%^MAmount complete =  78%^MAmount complete =  79%^MAmount complete =  80%^MAmount complete =  81%^MAmount complete =  82%^MAmount complete =  83%^MAmount complete =  84%^MAmount complete =  85%^MAmount complete =  86%^MAmount complete =  87%^MAmount complete =  88%^MAmount complete =  89%^MAmount complete =  90%^MAmount complete =  91%^MAmount complete =  92%^MAmount complete =  93%^MAmount complete =  94%^MAmount complete =  95%^MAmount complete =  96%^MAmount complete =  97%^MAmount complete =  98%

Done.`

**Comment by Tom111-lhx** [comment]
Done.
             Data points written:  525600

Error in chkfopen(): No such file or directory

**Comment by W-Hsu** [comment]
Can you run the whole routine correctly?

**Comment by Tom111-lhx** [comment]
Is it a  presto version issue? no ,I stopped at
 ================sifting candidates==================
Traceback (most recent call last):
  File "pipeline.py", line 293, in <module>
    cands = ACCEL_sift(zmax)
  File "pipeline.py", line 251, in ACCEL_sift
    if len(re.findall("_[0-9][0-9][0-9]M_" , inffiles[0])):
and I read the pipeline.py,.May be there is something about prepsubband.c.

**Comment by Tom111-lhx** [comment]
I use the latest presto-master(presto3.0.1).

**Comment by Tom111-lhx** [comment]
I installed presto with fftw , tempo , cfisio , pgplot environments,and I do `make makewisdom ;make prep ; make ;cd .. ; pip install .`.I guess everything is OK,but I do python GBT... pipeline.py ,there are someting wrong .

**Comment by W-Hsu** [comment]
No, I'm using the latest version too.
I just re-checked my dedisperse.log file, and I do find that I have the same problem...
![图片](https://user-images.githubusercontent.com/43788997/103868754-46887880-5104-11eb-8583-c8138c9abb68.png)
But I have the correct results at last. According to your error message `if len(re.findall("[0-9][0-9][0-9]M" , inffiles[0])):` I suggest you check if the files generate properly in subbands/ directory.

**Comment by Tom111-lhx** [comment]
in my dedisperse.log ,I just have .dat .fft ,but no .inf , and all my ".dat",".fft"file is empty.

**Comment by Tom111-lhx** [comment]
Must I install sigproc,and tempo2 or other things which are not in INSTALL guide.

**Comment by W-Hsu** [comment]
TEMPO is a must. 
btw. Are your environment variables set? Or are you using self-compile libraries or the apt/yum ones?

**Comment by Tom111-lhx** [comment]
I just see that in my subbands:
-rw-rw-r-- 1 wangsijun wangsijun 29380 Jan  7 16:39 accelsearch.log
-rw-rw-r-- 1 wangsijun wangsijun 43749 Jan  7 16:39 dedisperse.log
-rw-rw-r-- 1 wangsijun wangsijun 11236 Jan  7 16:39 fft.log
-rw-rw-r-- 1 wangsijun wangsijun     0 Jan  7 16:39 Sband_DM81.00.fft
-rw-rw-r-- 1 wangsijun wangsijun     0 Jan  7 16:39 Sband_DM81.50.dat
-rw-rw-r-- 1 wangsijun wangsijun     0 Jan  7 16:39 Sband_DM81.50.fft
-rw-rw-r-- 1 wangsijun wangsijun     0 Jan  7 16:39 Sband_DM82.00.dat
-rw-rw-r-- 1 wangsijun wangsijun     0 Jan  7 16:39 Sband_DM82.00.fft
-rw-rw-r-- 1 wangsijun wangsijun     0 Jan  7 16:39 Sband_DM82.50.dat
-rw-rw-r-- 1 wangsijun wangsijun     0 Jan  7 16:39 Sband_DM82.50.fft
-rw-rw-r-- 1 wangsijun wangsijun     0 Jan  7 16:39 Sband_DM83.00.dat
-rw-rw-r-- 1 wangsijun wangsijun     0 Jan  7 16:39 Sband_DM83.00.fft
-rw-rw-r-- 1 wangsijun wangsijun     0 Jan  7 16:39 Sband_DM83.50.dat

**Comment by Tom111-lhx** [comment]
`#!/bin/bash
PATH=$PATH:$HOME/bin:/home/wangsijun/project/task6/astrosoft/presto/bin:/home/wangsijun/project/task6/astrosoft/pgplot/bin:/home/wangsijun/project/task6/astrosoft/presto/bin:/nfshome/mcc/pfits:/home/wangsijun/project/task6/astrosoft/optimus:/home/wangsijun/project/task6/astrosoft/fv:/home/wangsijun/project/task6/astrosoft/psrcat_tar:/home/wangsijun/project/task6/astrosoft/tempo/src/
LD_LIBRARY_PATH=/home/wangsijun/project/task6/astrosoft/presto/lib:/home/wangsijun/project/task6/astrosoft/pgplot:/home/wangsijun/project/task6/astrosoft/fftw/lib:/home/wangsijun/project/task6/astrosoft/cfitsio/lib
C_INCLUDE_PATH=/home/wangsijun/project/task6/astrosoft/presto/include:/home/wangsijun/project/task6/astrosoft/cfitsio/include
PKG_CONFIG_PATH=/home/wangsijun/project/task6/astrosoft/cfitsio/lib/pkgconfig:/home/wangsijun/project/task6/astrosoft/fftw/lib/pkgconfig
PYTHONPATH=/home/wangsijun/project/task6/astrosoft/presto/lib/python:/home/wangsijun/project/task6/astrosoft/presto/python
PGPLOT_DIR=/home/wangsijun/project/task6/astrosoft/pgplot
PGPLOT_FONT=/home/wangsijun/project/task6/astrosoft/pgplot/grfont.dat
PGPLOT_DEV=/xwine
PGPLOT_LIB="-L /usr/X11R6/lib -lX11 -L /home/wangsijun/project/task6/astrosoft/pgplot -lpgplot"
PRESTO=/home/wangsijun/project/task6/astrosoft/presto
TEMPO=/home/wangsijun/project/task6/astrosoft/tempo
PSRCAT_FILE=/home/wangsijun/project/task6/astrosoft/psrcat_tar/psrcat.db

#export PATH
export LD_LIBRARY_PATH
#export C_INCLUDE_PATH
#export PKG_CONFIG_PATH
#export PYTHONPATH
export PGPLOT_DIR
#export PGPLOT_FONT
#export PGPLOT_DEV
#export PGPLOT_LIB
export PRESTO
#export TEMPO
#export PSRCAT_FILE

ANACONDA=/home/wangsijun/project/apps/anaconda2
export PATH="$ANACONDA/bin:$PATH"`

**Comment by Tom111-lhx** [comment]
I set my library in /task6/sentenv1.sh

**Comment by Tom111-lhx** [comment]
I do it on cloud platform, not on my own computer.

**Comment by W-Hsu** [comment]
Try to use the pgplot5 installed with apt (if your os is debian/ubuntu)
The self-compiled soft can cause trouble.

**Comment by Tom111-lhx** [comment]
but I am not the root user in the cloud platform, and in the cloud platform, my os is centos.

**Comment by Tom111-lhx** [comment]
my install step :
download:ftp://ftp.astro.caltech.edu/pub/pgplot/pgplot5.2.tar.gz
cd /home/m/Download
wget ftp://ftp.astro.caltech.edu/pub/pgplot/pgplot5.2.tar.gz
tar -zxvf pgplot5.2.tar.gz
mkdir /home/m/astrosoft/pgplot
cd /home/m/astrosoft/pgplot
cp /home/m/Download/pgplot/drivers.list .
vi drivers.list 
add:PS X-windows VPS、CPS,VCPS
do:/home/m/astrosoft/new/pgplot/makemake /home/m/astrosoft/new/pgplot linux g77_gcc
drivers.list grexec.f grpckg1.inc makefile pgplot.inc rgb.txt
vi makefile 
FCOMPL=g77 >FCOMPL=gfortran
sudo yum install libX11-devel
make
make cpg

**Comment by W-Hsu** [comment]
Hmm.. Seems to have no problem.
I just noticed that something may be wrong with the second line's tail of your setenv1.sh
`PATH=$PATH:.../home/wangsijun/project/task6/astrosoft/tempo/src/`, why not tempo/bin? Can you call the tempo command?
btw. Don't run your setenv1.sh like `./setenv1.sh`, use `. setenv1.sh` instead.

**Comment by Tom111-lhx** [comment]
so I should modify it ,should I remake in presto/src.

**Comment by W-Hsu** [comment]
Make it with a prefix. Like:
```bash
./configure --prefix=/home/wangsijun/project/task6/astrosoft/tempo/
make
make install
```

**Comment by Tom111-lhx** [comment]
in /presto/src ?

**Comment by W-Hsu** [comment]
No. If you can't find your `tempo` command, in tempo/bin, maybe you need to rebuild tempo.
If the new tempo PATH is set, maybe you don't have to rebuild PRESTO.

**Comment by Tom111-lhx** [comment]
OK,I will try it

**Comment by Tom111-lhx** [comment]
what's your fftw version I use fftw-3.3.5

**Comment by Tom111-lhx** [comment]
Ummm,I still failed

**Comment by Tom111-lhx** [comment]
do you creat ".inf "file in your subbands?

**Comment by Tom111-lhx** [comment]
Maybe something wrong with PSRFITS，SIGPROC，I have not install it

**Comment by W-Hsu** [comment]
I use fftw3.3.8.
It is really confusing. I cannot think of better solutions.

**Comment by Tom111-lhx** [comment]
can you give me some of your result and Path,I want find something different.

**Comment by Tom111-lhx** [comment]
and I want to know if there is .inf in your dedisperse.log. I feel crazy and tired about the presto .

**Comment by W-Hsu** [comment]
```
export PGPLOT_DIR=/usr/lib/pgplot5
export PRESTO=/home/whsu/opt/presto
export TEMPO=/home/whsu/opt/tempo
PATH=$PRESTO/bin:$PATH
PATH=$TEMPO/bin:$PATH
export PATH
```
These are all the environments that I set.
There is no inf file mentioned in my dedisperse.log. However, the inf files are created during prepsubband.

**Comment by Tom111-lhx** [comment]
but where are your fftw or cfisio's path?

**Comment by W-Hsu** [comment]
I installed them with my package manager - rather than compile them all by myself.
The pkg-config command invoked in $PRESTO/src/Makefile will handle it automatically.

**Comment by Tom111-lhx** [comment]
can i do The pkg-config command on centos?

**Comment by W-Hsu** [comment]
It shall be universal. But it needs *.ps files as its guide... The configuration is rather complex.
Are you preparing for the ASC competition? Maybe you should consult your teacher.
If you can get access to root permission, you can have a try on your package manager.

**Comment by Tom111-lhx** [comment]
He said that maybe there are something wrong about the pipeline.py. because He thought my enxironment is right.

**Comment by Tom111-lhx** [comment]
I rebuild the presto ,and do the command:
File "/home/wangsijun/project/task5/astrosoft/presto/python/presto/sifting.py", line 13, in <module>
    from presto.presto import candidate_sigma
ImportError: No module named presto

**Comment by W-Hsu** [comment]
Yeah, you are very close to success.
Simply delete the parameter will work.

**Comment by Tom111-lhx** [comment]
where is parameter

**Comment by W-Hsu** [comment]
`cmp_sigma` on the error line.
I suppose there's incompatibilities between presto's versions.

**Comment by W-Hsu** [comment]
I thought of my own problem...never mind
So which line of pipeline.py raised this?

**Comment by Tom111-lhx** [comment]
sorry,I didn't understand,shall I need to delete the line in sifting.py or in pipeline.py

**Comment by Tom111-lhx** [comment]
File "pipeline.py", line 9, in <module>
    from presto import sifting
  File "/home/wangsijun/project/task5/astrosoft/presto/python/presto/sifting.py", line 13, in <module>
    from presto.presto import candidate_sigma
ImportError: No module named presto

**Comment by Tom111-lhx** [comment]
at the beginning, I modifed the line 9 which is "import sifting " to "from presto import sifting", and then the error appeared

**Comment by W-Hsu** [comment]
Can you import presto.presto in the interactive python?

**Comment by Tom111-lhx** [comment]
I do pip install .

**Comment by Tom111-lhx** [comment]
it is in /project/wangsijun/apps/anaconda2/lib/python2.7/site-packages

**Comment by W-Hsu** [comment]
You can try uninstall it first and install it...
It may work.

**Comment by Tom111-lhx** [comment]
I find that there is two presto, one is in presto/python/presto, the other is /home/wangsijun/project/apps/anaconda2/lib/python2.7/site-packages/presto/presto
do you think it is right,all the presto have sifting.py

**Comment by Tom111-lhx** [comment]
I don't know which is the real path that the pipeline.py run from .

**Comment by Tom111-lhx** [comment]
maybe the presto3.0.1 doesn't need the python.library.so my Path still have some problem?
